# Generated by Django 2.2.4 on 2019-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190804_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.CharField(max_length=10),
        ),
    ]
