# Generated by Django 2.2.4 on 2019-08-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_remove_city_city_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('country_code', 'name'), 'verbose_name_plural': 'cities'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='country_code',
        ),
    ]
